### ISSUE TITLE
apply: Searching for program: No such file or directory, pandoc

### ISSUE THREAD

**Issue by antoan** [alphapapa/pocket-reader.el#11]
Version: 20180819.2007
From MELPA

Hi there, many thanks for this tool. 

When pressing RET on a pocket item to open it with org-web-tools-read-url-as-org command as per the default setting - I get the error in the title.

Is pandoc required to be installed externally or do  I need something like pandoc-mode?

I can however view items with eww when using:
(setq pocket-reader-url-open-fn-map
    '((eww-browse-url "*")))

But it would be nice to open the item text in a window below with org.

**Comment by alphapapa** [comment]
The `org-web-tools-read-url-as-org` command requires that Pandoc be installed.  That's how it converts web pages to Org files.

**Comment by baracunatana** [comment]
New user here. I just installed pandoc and can use in my cmd. I can also see it in my path variable, but I'm still getting the `Searching for program: No such file or directory, pandoc`.
I'm using Doom Emacs in Windows 10.

**Comment by alphapapa** [comment]
@juanerasmoe You will need to ensure that the Pandoc executable is in the path that Emacs searches for executables.

**Comment by baracunatana** [comment]
Working now. Thanks.

For future reference, this is how I'm loading pocket-reader to fix this without messing the exec-path in my linux machine

```
(use-package! pocket-reader
  :init
  (when (memq window-system '(w32))
    (add-to-list 'exec-path "C:\\Program Files\\Pandoc")))
```
