### ISSUE TITLE
Why are there empty lines?

### ISSUE THREAD

**Issue by xuchunyang** [alphapapa/pocket-reader.el#16]
I just get started using this cool package and notice there are some empty lines below some items, e.g., there are 4 empty lines in the following screenshot, what are they?

![image](https://user-images.githubusercontent.com/4550353/53506302-a9fcf480-3af0-11e9-951c-de58fe708c2e.png)

**Comment by alphapapa** [comment]
The blank lines group items by the selected sort column.  Please see the description and screenshots in the readme.
