### ISSUE TITLE
Some tags gets colorized when the title contains Chinese

### ISSUE THREAD

**Issue by xuchunyang** [alphapapa/pocket-reader.el#17]
It seems all tags should not be colorized, but in the following, the tags of these items with Chinese in their titles are also colorized for some reason, it looks like a bug to me.

![image](https://user-images.githubusercontent.com/4550353/53506543-2263b580-3af1-11e9-9db4-814f3e086238.png)

**Comment by alphapapa** [comment]
Please see the function `pocket-reader--column-data`.  I'm guessing this is a bug in the built-in `tabulated-list` library in that it doesn't handle multibyte characters properly when calculating column widths.  If so, we may be able to work around it, but a bug should be filed on Emacs itself.

**Comment by alphapapa** [comment]
Should be fixed in https://github.com/alphapapa/pocket-reader.el/commit/b56bcd3abb8aaecf1921b7db54db9d3b1290917b
