### ISSUE TITLE
Add feedback when archive/readd item

### ISSUE THREAD

**Issue by huangyg11** [alphapapa/pocket-reader.el#18]
When pressed a to toggle archive status, I have no idea if it is succeed or fail. I have to press G to refresh all.

maybe changed the background of the item when succeed?

**Comment by alphapapa** [comment]
Hi,

Actually, the faces are changed, which you can see in the functions `pocket-reader--archive-items` and `pocket-reader--readd-items`.  If that doesn't seem to be working for you, either there's a problem causing the archive/readd action to fail, or maybe you're not using distinctive faces for archived/unarchived status.

**Comment by huangyg11** [comment]
Thank you. The default difference on face is the font weight which make it not distinctive in my environment. I customize the face to adding strike-through  when archived.
