### ISSUE TITLE
Pocket sometimes returns null URLs, which causes wrong type argument errors

### ISSUE THREAD

**Issue by nobv** [alphapapa/pocket-reader.el#20]
I could authorization, and created `~/.cache/emacs-pocket-lib-token.json` correctly.
But I can't see my pocket list with `pocket-reader--url-domain: Wrong type argument: arrayp, nil` error.

How I can see my pocket list?

**Comment by alphapapa** [comment]
You would have to provide much more information in order for me to diagnose the problem.  Perhaps it's related to #19, but who knows.

**Comment by baracunatana** [comment]
I have the exact same issue. 

I know nothing about edebug and very little about elisp, but here's what I've done to find a solution:

- Completed the authorization process
- use edebug to stop the execution of `pocket-reader--url-domain`. That revealed that the authorization was successful and pocket-list was able to download my list.
- Modified the code of `pocket-reader--url-domain` this way:
```
(defun pocket-reader--url-domain (url)
  "Return domain for URL.
Common prefixes like www are removed."
  (message (concat "url: " url))
  (replace-regexp-in-string (rx bos (and (or "www" "amp") ".")) ""
                            (url-host (url-generic-parse-url url))))
```
Now, after running `pocket-reader`, I see the list of urls in my list BUT it stops when it find a nil url. I started deleting the bad url (examples at the end of this post) and it worked. Then I re-added the bad urls and sure enough I got the error message again.

Maybe there is something weird about those urls that breaks something in pocket-reader, but I have no idea of where to go from here in terms of fixing it

Bad url:
- https://www.amazon.com/Art-Enterprise-Information-Architecture-Systems-Based/dp/0137035713
- https://www.afp.com/es/noticias/838/la-trama-de-sangre-de-los-militares-en-colombia-doc-1rd2rq2

**Comment by alphapapa** [comment]
I'm beginning to wonder if Pocket has changed something on their end that is returning empty or null URL fields.  I guess we'll have to handle them.

**Comment by christofdamian** [comment]
I am now also running into this. This makes it impossible to use pocket-reader until you find the broken entry and remove it. 

The backtrace helped me to find one `resolved_url` that was empty.

Here is a back-trace (I edited it down to the broken entry)
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\`\\(?:amp\\|www\\)\\." "" nil)
  pocket-reader--url-domain("")xpo
  pocket-reader--get-url(#<hash-table eq 21/65 0x13aa221>)
 pocket-reader--add-items(( (\3035643357 (item_id . "3035643357") (resolved_id . "0") (given_url . "https://www.oxfordproducts.com/motorcycle/brands/oxford/battery_care_and_power_accessories/oxford_solariser/") (given_title . "Oxford Solariser : Oxford Products") (favorite . "0") (status . "0") (time_added . "1593624733") (time_updated . "1593624735") (time_read . "0") (time_favorited . "0") (sort_id . 11) (resolved_title . "") (resolved_url . "") (excerpt . "") (is_article . "0") (is_index . "0") (has_video . "0") (has_image . "0") (word_count . "0") (lang . "") (listen_duration_estimate . 0)) ))
  pocket-reader-search(nil)
  pocket-reader-refresh()
  pocket-reader-mode()
  pocket-reader()
  funcall-interactively(pocket-reader)
  call-interactively(pocket-reader record nil)
  command-execute(pocket-reader record)
  execute-extended-command(nil "pocket-reader" nil)
  funcall-interactively(execute-extended-command nil "pocket-reader" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
