### ISSUE TITLE
Amazing Pocket + Emacs experience

### ISSUE THREAD

**Issue by punassuming** [alphapapa/pocket-reader.el#25]
@alphapapa , this has become my primary interface to pocket lately.  Thank you very much for putting it together.  I am going to start looking the code, as recently I tried switching over to a self-hosted wallabag to get better control of my links.  Do you think it would be difficult to rewrite this to work within the wallabag apis?

**Comment by alphapapa** [comment]
I'm glad it's been helpful to you.

I've never looked at the Wallabag APIs.  If they are similar to Pocket's, I guess it shouldn't be too difficult to adapt.

**Comment by alphapapa** [comment]
AFAIK there's a Wallabag package out there somewhere now...
