### ISSUE TITLE
Why are parts of some URLs colored?

### ISSUE THREAD

**Issue by oantolin** [alphapapa/pocket-reader.el#36]
![image](https://user-images.githubusercontent.com/2635478/151671817-62c8863b-59b3-4f01-94cf-aa318b16d348.png)

This doesn't actually bother me, but I do find it unusual that for some URLs in the "Site" column the initial portion is colored the same color as the title. Look at proteanmag which is colored up to the m, or getpocket.com which is colored upto the c in com. Weird, right?

**Comment by alphapapa** [comment]
I don't know, I've never seen that behavior.  You could try using `C-u C-x =` to examine the faces of those characters.

**Comment by alphapapa** [comment]
@oantolin Given the information in #40, I'm guessing this bug is caused by changes in `tabulated-list-mode` in newer Emacs versions.  What version are you using?

**Comment by oantolin** [comment]
I'm using a build of Emacs 28.0.50 from april 2021, so moderately new.

**Comment by alphapapa** [comment]
Thanks.
