### ISSUE TITLE
Authorization URL no longer working

### ISSUE THREAD

**Issue by junjizhi** [alphapapa/pocket-reader.el#37]
I installed pocket-reader the first time, followed the instructions in Emacs prompt, and pasted the URL on the browser, pressed the authorize button, and I got the 404 response:

 
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2715151/152688136-97421c05-736f-4342-8e0d-076a8bbc142e.png">

`~/.cache/emacs-pocket-lib-token.json` seems to be populated fine with the access_token and username fields, so the problem seems to be on the Pocke's side.

Anyone had it working recently?

**Comment by junjizhi** [comment]
Nvm. The 404 is expected from the README. It was actually working.

**Comment by iT-Boyer** [comment]
I have the same problem , but  in the json file:
```
undefined
```

**Comment by alphapapa** [comment]
@iT-Boyer I just tested this a week or two ago and it worked fine.  If it still doesn't work for you, please open a new issue with as much detail as you can provide.
