### ISSUE TITLE
Support/document the special _untagged_ tag

### ISSUE THREAD

**Issue by kaya-toast** [alphapapa/pocket-reader.el#38]
Thank you for creating this package! I have been really frustrated with how slow the Pocket desktop app and the web interface are, so I'm really glad to have found this.

Is it possible to search for articles that do not have any tags? The Pocket desktop/iOS app has the function to search for untagged items, and I'm wondering if I can do the same thing in pocket-reader.

Thanks again!

**Comment by bcc32** [comment]
You can actually search for the special tag `_untagged_` (press `t s` to tag search), which will give you the list of articles with no tags.  This is explained on the Pocket [API documentation](https://getpocket.com/developer/docs/v3/retrieve) but I don't think it's mentioned in pocket-reader.el's docs.

**Comment by kaya-toast** [comment]
It works! Thank you so much @bcc32 
I will close this issue now.

**Comment by alphapapa** [comment]
Thanks, @bcc32, I didn't know about that special tag.  We should do something with it in this package someday...
