### ISSUE TITLE
Fresh install of pocket-reader from melpa can't authorized with supplied link

### ISSUE THREAD

**Issue by pidu** [alphapapa/pocket-reader.el#39]
This is what pocket says:

![image](https://user-images.githubusercontent.com/4929249/154671018-758ff784-6856-4274-b425-e90312fec2c9.png)

Emacs version: 27.1

**Comment by alphapapa** [comment]
Did you try multiple times?  I recall encountering errors like this sometimes, and that trying again would fix it.  If not, maybe they changed something in the API, which wouldn't surprise me.

**Comment by pidu** [comment]
Yes, I tried a couple of times from two different computers.

**Comment by alphapapa** [comment]
Ok, thanks.  I probably won't have time to work on this soon, so any help would be appreciated.

**Comment by danielfleischer** [comment]
I also got an error, but everything works; pocket-reader can access my items, read them, archive, etc.

**Comment by nullman** [comment]
> I also got an error, but everything works; pocket-reader can access my items, read them, archive, etc.

I had the same experience.

**Comment by alphapapa** [comment]
Yes, this has been my experience as well: the site shows an error, but then the token works anyway.  That's why I added this note in the readme 3 years ago: https://github.com/alphapapa/pocket-reader.el/commit/05b6baa869ffe3b67880e32443844a9a1e2ee310
