### ISSUE TITLE
Tags containing spaces not working

### ISSUE THREAD

**Issue by pataquets** [alphapapa/pocket-reader.el#43]
I have several items tagged `view online`  and I can't search them using `pocket-reader-search`.
Looking at the code, query is split just by spaces alone, without any parsing for space-containing tags.
Possible solutions:
* Interpret an escaped space, such as `\SPC`.
* Account for tags enclosed in single/double quotes, by inhibiting space-splitting inside.

**Comment by alphapapa** [comment]
Thanks, this should be fixed, indeed.  I don't know how soon I'll have time to work on this, so patches welcome.

**Comment by pataquets** [comment]
Glad to hear it, thank you. Unfortunately, still novice Elisp'er here.
However, any directions on your preferred approach (UX and code-wise) and other advice you may provide will be appreciated and, maybe in the future it could be useful for me or others going thru this issue and ready to pick it up.
I've seen a handful of functions in the code needing love, which suggests me the issue should be broken in parts to qualify as "low hanging fruit" / "good first issue".

**Comment by alphapapa** [comment]
> Glad to hear it, thank you. Unfortunately, still novice Elisp'er here.
> However, any directions on your preferred approach (UX and code-wise)
> and other advice you may provide will be appreciated and, maybe in the
> future it could be useful for me or others going thru this issue and
> ready to pick it up.

I don't have much advice about this.  It should be relatively simple to parse the string given by the user for any segments enclosed in quotes.  Since the syntax is basically Lisp syntax, you can probably use the READ function.

> I've seen a handful of functions in the code needing love, which
> suggests me the issue should be broken in parts to qualify as "low
> hanging fruit" / "good first issue".

You'd have to be more specific about which functions you mean.

**Comment by alphapapa** [comment]
@pataquets This should be fixed now.  Please let me know if it works for you.

**Comment by pataquets** [comment]
@alphapapa Tested. function works OK, thanks!
Filed related issue: #46.
