### ISSUE TITLE
Doesn't work on Windows OS (Emacs 29.1)

### ISSUE THREAD

**Issue by mateialexandru** [alphapapa/pocket-reader.el#49]
On Windows OS, after finishing authentication with the browser and running again `pocket-reader` I get an error message:
```
cl-no-applicable-method: No applicable method: map-do, #[514 "   T  " [(0)] 4 " 

```

I am wondering if this is something to do with the `url-retrieve` behavior on Windows, where it has various issues and maybe we are running into such kind of problems with the `pocket-reader` requests. @skeeto referred to this kind of issues in https://github.com/skeeto/elfeed?tab=readme-ov-file#prerequisites

**Comment by mateialexandru** [comment]
Indeed, on the same device, when using Emacs WSL everything works, while when using Emacs native Windows build I get this weird error.

@alphapapa can we entertain using CURL as a workaround?

**Comment by alphapapa** [comment]
@mateialexandru In order to understand the problem, we need to see the backtrace.  `M-x toggle-debug-on-error RET` and cause the error again, please.  Since neither `pocket-reader` nor `pocket-lib` use the `map` library, it's unlikely that the problem you're having is related to those libraries.

**Comment by mateialexandru** [comment]
Thanks @alphapapa ! Sorry, I just saw the notification and I appreciate the suggestion.  
Right now, I moved to Emacs on WSL and this package is working great!


Since it is good to follow-up on the original issue, I installed the native Windows version of Emacs and collected this stack trace:


Debugger entered--Lisp error: (cl-no-applicable-method map-do #f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403)
  signal(cl-no-applicable-method (map-do #f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403))
  cl-no-applicable-method(#s(cl--generic :name map-do :dispatches ((1 #s(cl--generic-generalizer :name cl--generic-typeof-generalizer :priority 10 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x5c321d2ad433562>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x1a89f131959b5800>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x1cba0b13a96764e4>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x2b662d08469105e>))) (0 #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x1cba0b13a96764e4>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x2b662d08469105e>)))) :method-table (#s(cl--generic-method :specializers (t array) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode -0xa3527a587915847>)) #s(cl--generic-method :specializers (t list) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode -0x105fba7f014a14f6>)) #s(cl--generic-method :specializers (t hash-table) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode 0xecf986e6c041016>))) :options nil) #f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403)
  apply(cl-no-applicable-method #s(cl--generic :name map-do :dispatches ((1 #s(cl--generic-generalizer :name cl--generic-typeof-generalizer :priority 10 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x5c321d2ad433562>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x1a89f131959b5800>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x1cba0b13a96764e4>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x2b662d08469105e>))) (0 #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode -0x1cba0b13a96764e4>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode -0x2b662d08469105e>)))) :method-table (#s(cl--generic-method :specializers (t array) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode -0xa3527a587915847>)) #s(cl--generic-method :specializers (t list) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode -0x105fba7f014a14f6>)) #s(cl--generic-method :specializers (t hash-table) :qualifiers nil :call-con nil :function #f(compiled-function #'map #<bytecode 0xecf986e6c041016>))) :options nil) (#f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403))
  #f(compiled-function (&rest args) #<bytecode -0x79c8aae6d720105>)(#f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403)
  apply(#f(compiled-function (&rest args) #<bytecode -0x79c8aae6d720105>) #f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403 nil)
  map-do(#f(compiled-function (k v) #<bytecode 0x4c872f3ab2ac997>) 403)
  #f(compiled-function (map) #<bytecode -0x18e6ffaa64f25aad>)(403)
  apply(#f(compiled-function (map) #<bytecode -0x18e6ffaa64f25aad>) 403 nil)
  map-length(403)
  #f(compiled-function (map) #<bytecode 0x17a95c3c986b5345>)(403)
  apply(#f(compiled-function (map) #<bytecode 0x17a95c3c986b5345>) 403 nil)
  map-empty-p(403)
  json--print-map(403)
  json--print-alist(403)
  json-encode-alist(403)
  pocket-lib--save-access-token(403)
  pocket-lib--authorize()
  pocket-lib--request(get :data (:offset 0 :count 50 :detailType "complete" :state nil :favorite nil :tag nil :content-type nil :sort nil :search "" :domain nil :since nil) :sync t)
  pocket-lib-get(:detail-type "complete" :count 50 :offset 0 :search "" :state nil :favorite nil :tag nil)
  pocket-reader--get-items(nil)
  pocket-reader-search(nil)
  pocket-reader-refresh()
  pocket-reader-mode()
  pocket-reader()
  funcall-interactively(pocket-reader)
  command-execute(pocket-reader record)
  execute-extended-command(nil "pocket-reader" nil)
  funcall-interactively(execute-extended-command nil "pocket-reader" nil)
  command-execute(execute-extended-command)

**Comment by alphapapa** [comment]
Looks like you had a combination of a broken Emacs installation and an authorization failure (403).

**Comment by mateialexandru** [comment]
Thanks!
