### ISSUE TITLE
Running pocket-reader on Emacs 29.3 errors with a void symbol

### ISSUE THREAD

**Issue by AleksandarMicovic** [alphapapa/pocket-reader.el#50]
**Steps to reproduce**

1. Install pocket-reader from MELPA.
2. Run `pocket-reader` per README.
3. Receive error `Symbol's value as variable is void: auto-revert-notify-watch-descriptor-hash-list`

**Expected result**

3. I'm actually not sure as I've never run the package :) but I assume it's supposed to ask for authentication?

Let me know if I can do anything else to debug, or if there's an interim workaround.

**Comment by alphapapa** [comment]
Please note that the symbol `auto-revert-notify-watch-descriptor-hash-list` is not present in this package's source code.  As well, I use this package on Emacs 29.3 without any problem.  Therefore there must be a problem in your Emacs configuration or in another package you have installed.  I'd recommend testing in a clean configuration with https://github.com/alphapapa/with-emacs.sh

**Comment by AleksandarMicovic** [comment]
This actually seems to affect all packages using `request`, of which `pocket-reader` relies on as a dependency.

I wanted to follow up here just in case anyone else runs into this. You can fix the issue by manually applying [this commit](https://github.com/tkf/emacs-request/commit/0183da84cb45eb94da996cd2eab714ef0d7504cc) to `request`. There's a small conversation about this [here](https://github.com/tkf/emacs-request/issues/219).

Thanks @alphapapa for the testing script. Led me down this rabbit hole.

**Comment by alphapapa** [comment]
@AleksandarMicovic Ah, an unfortunate situation.  I guess you're using MELPA Stable in your config?  This sort of thing is one of the reasons it's not generally recommended to use MELPA Stable.  I remember now seeing that workaround in `request` and being puzzled by it.

Anyway, I guess I should switch `pocket-lib` to use `plz` at this point.
