### ISSUE TITLE
Bug: getting `wrong type argument: arrayp, nil` and no entries when using the  `pocket-reader` command.

### ISSUE THREAD

**Issue by shard77** [alphapapa/pocket-reader.el#55]
Hello, I'm getting an issue when trying to execute the `pocket-reader` command.
I am correctly authenticated and I have multiple saves in pocket.
It worked once, but afterwards I tried to delete the entry and add other ones through the package, I see the saves on the pocket site, but I get this error in emacs with the plugin.
Not sure what to do here, I went through some of the similar issues but nothing seemed to fix this.

**Comment by alphapapa** [comment]
Please provide the backtrace.  See also: https://github.com/alphapapa/pocket-reader.el/issues/54

**Comment by shard77** [comment]
> Please provide the backtrace. See also: #54

Sorry, after checking the backtrace, I've figured out it's the same bug as #54, closing this issue.
