### ISSUE TITLE
Document use of `pocket-reader-url-open-fn-map`

### ISSUE THREAD

**Issue by ninjawithaneedle** [alphapapa/pocket-reader.el#8]
I would like to be able to use `eww-browse-url` to open pocket links. Looks like the functionality is already built. https://github.com/alphapapa/pocket-reader.el/blob/master/pocket-reader.el#L825

I am new to elisp/emacs and couldn't figure out how to set this variable. It would help if it was documented.

Thanks

**Comment by alphapapa** [comment]
Good idea, thanks!

Were you able to figure it out with the help of the docstring?  https://github.com/alphapapa/pocket-reader.el/blob/master/pocket-reader.el#L203  Just do `M-x customize-variable RET pocket-reader-url-open-fn-map RET` and you can add new hostnames and functions.

**Comment by ninjawithaneedle** [comment]
It does make sense now. I added

```
  (setq pocket-reader-url-open-fn-map
    '((eww-browse-url "*")))
```

to my config to get it to work.

**Comment by alphapapa** [comment]
You can also set `pocket-reader-open-url-default-function`.
