### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by jinchengJL** [alphapapa/pocket-reader.el#9]
I'll admit first that I have no idea how dependency management for packages on MELPA work.

What happened to me was that after installing pocket-reader and trying to run it, it complains about missing a function `s-blank-str?`. I figured out I'm missing the `s.el` package, so I install it. Then it complains I'm missing `ht-get`, which requires installing the `ht.el` package. Is there a way to maybe make this more automatic?

**Comment by alphapapa** [comment]
`ht` and `s` are both declared as dependencies in the package headers.  If you install the package with `package.el` (the built-in Emacs package manager) from MELPA, all dependencies should be installed.  If that doesn't happen, I guess it is a configuration problem.

If you want to look into it, try installing the package in a clean Emacs config and see if the dependencies are installed.  If they are, you'll know it's an issue with your config.

**Comment by jinchengJL** [comment]
This worked on another install I had. Closing.
